version: "3.8"

volumes:
  call_for_papers_service_postgres_data:

services:
  database:
    image: 'postgres:15'
    environment:
      POSTGRES_USER: "hutao"
      POSTGRES_PASSWORD: "hutao"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - call_for_papers_service_postgres_data:/var/lib/postgresql/data

  call_for_papers_service:
    build:
      context: .
      dockerfile: Api/Dockerfile

    ports:
      - "8080:8080"
    depends_on:
      - database